import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from './LogoutBtn';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // @ts-ignore
  let session = await getServerSession(authOptions);
  // console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          {/* <LoginBtn></LoginBtn> */}
          {
            session?(
              <span>{session.user?.name}님 환영합니다! <LogoutBtn></LogoutBtn></span>
            ):(
                <LoginBtn></LoginBtn>
            )
          }
        </div>
      {children}
      </body>
    </html>
  )
}
